import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import clsx from "clsx";
import "./globals.css";

const sans = Hanken_Grotesk({ subsets: ["latin"], variable: "--sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          sans.variable,
          "font-sans bg-neutral-950 text-neutral-300"
        )}
      >
        <main className="container max-w-lg mx-auto p-9">{children}</main>
      </body>
    </html>
  );
}
